#!/usr/bin/env python3
"""Repo invariant validator for the papers collection.

The repo is the source of truth: this script is stateless and derives
everything from the working tree on each run. It is the single check logic
behind three trigger points:

  * the git pre-commit hook (githooks/pre-commit)  — fail closed
  * Claude Code hooks (.claude/settings.json)      — fail open, feeds agents
  * manual runs                                    — report / --fix / --links

Usage:
  python3 scripts/validate.py                 report all findings
  python3 scripts/validate.py --fix           apply mechanical fixes, then report
  python3 scripts/validate.py --hook post-tool-use   (stdin: Claude hook JSON)
  python3 scripts/validate.py --hook stop            (stdin: Claude hook JSON)
  python3 scripts/validate.py --links         on-demand external link check

Exit codes: 0 clean (warnings allowed), 1 errors, 3 internal error.
Hook modes: 0 clean/irrelevant, 2 errors (stderr shown to the agent).
"""

import argparse
import json
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEARNING = ROOT / "learning"
GLOSSARY = LEARNING / "glossary.md"
BYDATE = ROOT / "by-date.md"
README = ROOT / "README.md"
LEARNING_PATH = ROOT / "learning-path.md"

COVERAGE_START = "<!-- COVERAGE:START (generated by scripts/validate.py --fix; do not hand-edit) -->"
COVERAGE_END = "<!-- COVERAGE:END -->"

# Curriculum order; label/emoji used for by-date back-links and the generated
# README coverage block. Files not listed here still validate (fallback label).
AREAS = [
    ("foundations", "🏗️", "Foundations"),
    ("language-models", "🤖", "Language Models"),
    ("attention", "⚡", "Attention"),
    ("retrieval", "🔍", "Retrieval & RAG"),
    ("reasoning", "🧠", "Reasoning & Agents"),
    ("architectures", "🏛️", "Architectures"),
    ("interpretability", "🔬", "Interpretability"),
    ("safety", "🛡️", "Safety & Security"),
    ("advanced", "🎯", "Advanced"),
    ("probabilistic", "🎲", "Probabilistic"),
    ("vision", "👁️", "Vision & Multimodal"),
    ("hardware", "⚙️", "Hardware & Systems"),
    ("human-ai-interaction", "🧠", "Human-AI Interaction"),
    ("policy", "📜", "Policy & Governance"),
]
AREA_LABEL = {stem: label for stem, _, label in AREAS}
AREA_EMOJI = {stem: emoji for stem, emoji, _ in AREAS}

# Hosts the --links checker skips: paywalled / anti-bot, always false-positive.
LINK_SKIP_HOSTS = {
    "journals.sagepub.com",
    "psycnet.apa.org",
    "academic.oup.com",
    "www.researchgate.net",
    "papers.ssrn.com",
    "www.cell.com",
    "leginfo.legislature.ca.gov",
    "capitol.texas.gov",
}
LINK_OK_CODES = {200, 201, 202, 203, 204, 403, 405, 429}

ARXIV_RE = re.compile(
    r"^https?://arxiv\.org/(?:abs|pdf)/(\d{4}\.\d{4,5})(?:v\d+)?(?:\.pdf)?/?$"
)
ENTRY_RE = re.compile(r"^(\d+)\.\s+((?:📄|🔒)\s+)?\[(.+?)\]\((\S+?)\)(.*)$")
BULLET_RE = re.compile(r"^- ((?:📄|🔒)\s+)?\[(.+?)\]\((\S+?)\)(.*)$")
AREA_LINK_RE = re.compile(r"\s+—\s+\[([^\]]+)\]\((learning/[a-z-]+\.md)\)\s*$")
MD_LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)\s]+)\)")


class Finding:
    def __init__(self, severity, file, line, check, message):
        self.severity = severity
        self.file = file
        self.line = line
        self.check = check
        self.message = message

    def render(self):
        return f"{self.severity} {self.file}:{self.line} [{self.check}] {self.message}"


class Repo:
    """Parsed model of the repo, rebuilt from disk on each construction."""

    def __init__(self):
        self.findings = []
        self.topic_files = sorted(
            p for p in LEARNING.glob("*.md") if p.name != "glossary.md"
        )
        self.topics = {}  # stem -> list of sections
        for path in self.topic_files:
            self.topics[path.stem] = self._parse_topic(path)
        self.bydate = self._parse_bydate()
        self.glossary_anchors, self.glossary_terms = self._parse_glossary()

    # -- helpers ----------------------------------------------------------
    def error(self, file, line, check, message):
        self.findings.append(Finding("ERROR", file, line, check, message))

    def warn(self, file, line, check, message):
        self.findings.append(Finding("WARN ", file, line, check, message))

    # -- parsing ----------------------------------------------------------
    def _parse_topic(self, path):
        sections = []
        current = None
        lines = path.read_text(encoding="utf-8").splitlines()
        for i, line in enumerate(lines, 1):
            if line.startswith("## "):
                current = {"name": line[3:].strip(), "line": i, "entries": []}
                sections.append(current)
            elif current is not None:
                m = ENTRY_RE.match(line)
                if m:
                    current["entries"].append(
                        {
                            "num": int(m.group(1)),
                            "line": i,
                            "emoji": (m.group(2) or "").strip(),
                            "title": m.group(3),
                            "url": m.group(4),
                            "rest": m.group(5),
                            "cont": [],
                        }
                    )
                elif re.match(r"^\d+\.\s", line):
                    self.error(
                        rel(path), i, "entry-format",
                        f'numbered item is not "[Title](url)" form: "{line[:60]}..." '
                        "-> use `N. [Title](url) (Authors, Year)` or an unnumbered bullet",
                    )
                elif current["entries"] and re.match(r"^\s+-\s", line):
                    current["entries"][-1]["cont"].append((i, line))
        return sections

    def _parse_bydate(self):
        model = {"years": [], "bullets": [], "footer": {}, "lines": []}
        lines = BYDATE.read_text(encoding="utf-8").splitlines()
        model["lines"] = lines
        year = None
        month = None
        for i, line in enumerate(lines, 1):
            if line.startswith("## ") and not line.startswith("###"):
                head = line[3:].strip()
                m = re.match(r"^(\d{4})$", head)
                year = {"raw": head, "line": i, "year": int(m.group(1)) if m else None,
                        "months": []}
                month = None
                model["years"].append(year)
                if not m:
                    self.error(
                        "by-date.md", i, "structure",
                        f'year heading "## {head}" not in "## YYYY" form '
                        "-> split/normalize into single-year sections",
                    )
            elif line.startswith("### "):
                head = line[4:].strip()
                m = re.match(r"^(\d{4})\.(\d{2})$", head)
                month = {"raw": head, "line": i,
                         "year": int(m.group(1)) if m else None,
                         "month": int(m.group(2)) if m else None}
                if year is not None:
                    year["months"].append(month)
                if not m:
                    self.error(
                        "by-date.md", i, "structure",
                        f'month heading "### {head}" not in "### YYYY.MM" form '
                        "-> normalize (e.g. venue/era labels become YYYY.MM or plain year section)",
                    )
                elif year is not None and year["year"] is not None and m and int(m.group(1)) != year["year"]:
                    self.error(
                        "by-date.md", i, "structure",
                        f'month "### {head}" sits inside "## {year["raw"]}" '
                        f"-> move it under ## {m.group(1)}",
                    )
            else:
                b = BULLET_RE.match(line)
                if b:
                    rest = b.group(4)
                    area = AREA_LINK_RE.search(rest)
                    if area:
                        rest_wo_area = rest[: area.start()]
                    else:
                        rest_wo_area = rest
                    model["bullets"].append(
                        {
                            "line": i,
                            "emoji": (b.group(1) or "").strip(),
                            "title": b.group(2),
                            "url": b.group(3),
                            "rest": rest_wo_area,
                            "area_label": area.group(1) if area else None,
                            "area_target": area.group(2) if area else None,
                            "year": year["year"] if year else None,
                            "month": month["month"] if month else None,
                        }
                    )
                m = re.match(r"^\*\*Total Papers in Learning Path\*\*: (\d+)", line)
                if m:
                    model["footer"]["total"] = (i, int(m.group(1)))
                m = re.match(r"^\*\*Paywalled Papers\*\*: (\d+)", line)
                if m:
                    model["footer"]["paywalled"] = (i, int(m.group(1)))
                m = re.match(r"^\*\*Open Access\*\*: ~?(\d+)%", line)
                if m:
                    model["footer"]["open"] = (i, int(m.group(1)))
        return model

    def _parse_glossary(self):
        anchors = set()
        terms = 0
        section = None
        seen = defaultdict(int)
        for line in GLOSSARY.read_text(encoding="utf-8").splitlines():
            if line.startswith("## ") and not line.startswith("###"):
                section = line[3:].strip()
            for level in ("## ", "### ", "#### "):
                if line.startswith(level) and not line.startswith("#" + level):
                    slug = github_slug(line[len(level):].strip())
                    if seen[slug]:
                        anchors.add(f"{slug}-{seen[slug]}")
                    else:
                        anchors.add(slug)
                    seen[slug] += 1
                    break
            if line.startswith("### ") and section not in (
                "Table of Contents", "Cross-References", "Acronyms Quick Reference",
            ):
                terms += 1
        return anchors, terms

    # -- derived data ------------------------------------------------------
    def topic_entries(self):
        for stem, sections in self.topics.items():
            for sec in sections:
                for e in sec["entries"]:
                    yield stem, sec, e

    def topic_urls(self):
        urls = defaultdict(list)  # canon -> [(stem, entry)]
        for stem, sec, e in self.topic_entries():
            urls[canon(e["url"])].append((stem, e))
        return urls

    def counts(self):
        per_area = {stem: sum(len(s["entries"]) for s in secs)
                    for stem, secs in self.topics.items()}
        distinct = len(self.topic_urls())
        policy_docs = sum(
            1 for stem, sec, e in self.topic_entries()
            if stem == "policy" and e["emoji"] == "📄"
        )
        bydate_total = len(self.bydate["bullets"])
        bydate_paywalled = sum(1 for b in self.bydate["bullets"] if b["emoji"] == "🔒")
        return {
            "per_area": per_area,
            "distinct": distinct,
            "policy_docs": policy_docs,
            "areas": len(self.topic_files),
            "glossary_terms": self.glossary_terms,
            "bydate_total": bydate_total,
            "bydate_paywalled": bydate_paywalled,
        }


def rel(path):
    return str(Path(path).resolve().relative_to(ROOT))


def canon(url):
    m = ARXIV_RE.match(url)
    if m:
        return f"arxiv:{m.group(1)}"
    url = url.replace("http://", "https://")
    return url.rstrip("/")


def github_slug(heading):
    # GitHub's anchor algorithm: lowercase, drop everything that is not a word
    # character, space, or hyphen, then spaces -> hyphens. Emoji vanish but
    # their trailing space survives, producing a leading hyphen.
    text = heading.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    return text.replace(" ", "-")


# ---------------------------------------------------------------------------
# checks
# ---------------------------------------------------------------------------

def check_cross_index(repo):
    topic_urls = repo.topic_urls()
    bydate_urls = defaultdict(list)
    for b in repo.bydate["bullets"]:
        bydate_urls[canon(b["url"])].append(b)
    for cu, owners in sorted(topic_urls.items(), key=lambda kv: kv[1][0][1]["line"]):
        if cu not in bydate_urls:
            stem, e = owners[0]
            repo.error(
                f"learning/{stem}.md", e["line"], "cross-index",
                f'"{e["title"][:60]}" ({cu}) not in by-date.md '
                "-> run: python3 scripts/validate.py --fix (auto-inserts by year), "
                "or add the bullet by hand",
            )
    for cu, bullets in sorted(bydate_urls.items(), key=lambda kv: kv[1][0]["line"]):
        if cu not in topic_urls:
            b = bullets[0]
            repo.error(
                "by-date.md", b["line"], "cross-index",
                f'"{b["title"][:60]}" ({cu}) is in by-date.md but no learning/*.md topic file '
                "-> add it to the best-fit topic file or remove this bullet",
            )


def check_duplicates(repo):
    for stem, sections in repo.topics.items():
        seen = {}
        for sec in sections:
            for e in sec["entries"]:
                cu = canon(e["url"])
                if cu in seen:
                    repo.error(
                        f"learning/{stem}.md", e["line"], "duplicate-url",
                        f"{cu} already listed at learning/{stem}.md:{seen[cu]} "
                        "-> keep one numbered entry; make the other an unnumbered *See also* line",
                    )
                else:
                    seen[cu] = e["line"]
    seen = {}
    for b in repo.bydate["bullets"]:
        cu = canon(b["url"])
        if cu in seen:
            repo.error(
                "by-date.md", b["line"], "duplicate-url",
                f"{cu} already listed at by-date.md:{seen[cu]} -> remove one bullet",
            )
        else:
            seen[cu] = b["line"]


def check_anchors(repo):
    # All internal .md#anchor links must resolve; glossary anchors are the
    # historically broken ones but every heading target is checked.
    heading_cache = {}

    def anchors_of(path):
        if path not in heading_cache:
            anchors = set()
            seen = defaultdict(int)
            try:
                for line in path.read_text(encoding="utf-8").splitlines():
                    m = re.match(r"^(#{1,6})\s+(.*)$", line)
                    if m:
                        slug = github_slug(m.group(2).strip())
                        anchors.add(slug if not seen[slug] else f"{slug}-{seen[slug]}")
                        seen[slug] += 1
            except OSError:
                pass
            heading_cache[path] = anchors
        return heading_cache[path]

    for path in [README, LEARNING_PATH, BYDATE, *repo.topic_files, GLOSSARY]:
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError:
            continue
        for i, line in enumerate(lines, 1):
            for m in MD_LINK_RE.finditer(line):
                target = m.group(2)
                if target.startswith(("http://", "https://", "mailto:")) or "?" in target:
                    continue  # external URLs and GitHub-web links (issues/new?template=...)
                base, _, frag = target.partition("#")
                resolved = (path.parent / base).resolve() if base else path
                if base and not resolved.exists():
                    repo.warn(
                        rel(path), i, "rel-link",
                        f'link target "{base}" does not exist -> fix the relative path',
                    )
                    continue
                if frag and resolved.suffix == ".md" and resolved.exists():
                    if frag not in anchors_of(resolved):
                        check_id = ("glossary-anchor" if resolved == GLOSSARY else "anchor")
                        repo.error(
                            rel(path), i, check_id,
                            f'anchor "#{frag}" not found in {rel(resolved)} '
                            "-> add the heading/term or fix the link",
                        )


def check_order(repo):
    years = [y for y in repo.bydate["years"] if y["year"] is not None]
    for prev, cur in zip(years, years[1:]):
        if cur["year"] >= prev["year"]:
            repo.error(
                "by-date.md", cur["line"], "order",
                f'"## {cur["raw"]}" appears after "## {prev["raw"]}" '
                "-> years must be strictly descending; run --fix to reorder",
            )
    for y in years:
        months = [m for m in y["months"] if m["month"] is not None and m["year"] == y["year"]]
        for prev, cur in zip(months, months[1:]):
            if cur["month"] >= prev["month"]:
                repo.error(
                    "by-date.md", cur["line"], "order",
                    f'"### {cur["raw"]}" appears after "### {prev["raw"]}" '
                    "-> months must be descending within a year; run --fix to reorder",
                )


def check_entry_format(repo):
    for stem, sections in repo.topics.items():
        file = f"learning/{stem}.md"
        for sec in sections:
            for idx, e in enumerate(sec["entries"], 1):
                if e["num"] != idx:
                    repo.error(
                        file, e["line"], "entry-format",
                        f'entry numbered {e["num"]}, expected {idx} in section '
                        f'"{sec["name"]}" -> run --fix to renumber',
                    )
                indent = len(f"{e['num']}. ")
                for line_no, cont in e["cont"]:
                    actual = len(cont) - len(cont.lstrip())
                    # deeper indents are legitimate nested lists; only
                    # under-indentation breaks GitHub's list nesting
                    if actual < indent:
                        repo.error(
                            file, line_no, "entry-format",
                            f"continuation bullet indented {actual} spaces, needs at least {indent} "
                            "(aligns under the title) -> re-indent",
                        )
                has_why = any("*Why*" in cont for _, cont in e["cont"])
                if not has_why:
                    repo.warn(
                        file, e["line"], "entry-format",
                        f'"{e["title"][:50]}" has no `- *Why*:` annotation -> add one (1-2 sentences)',
                    )


def check_bydate_format(repo):
    topic_urls = repo.topic_urls()
    paywalled_topic = {
        canon(e["url"]) for _, _, e in
        ((s, sec, e) for s, sec, e in repo.topic_entries())
        if e["emoji"] == "🔒"
    }
    for b in repo.bydate["bullets"]:
        cu = canon(b["url"])
        if b["area_target"] is None:
            if cu in topic_urls:
                repo.error(
                    "by-date.md", b["line"], "bydate-format",
                    f'"{b["title"][:50]}" has no area back-link '
                    "-> run --fix to append “ — [Area](learning/<area>.md)”",
                )
        else:
            target = ROOT / b["area_target"]
            stem = target.stem
            in_target = any(s == stem for s, _ in topic_urls.get(cu, []))
            if not in_target:
                repo.error(
                    "by-date.md", b["line"], "bydate-format",
                    f'area back-link points to {b["area_target"]} which does not contain {cu} '
                    "-> point it at the topic file that lists this paper",
                )
        if b["emoji"] == "🔒" and "*Paywalled*" not in b["rest"]:
            repo.error(
                "by-date.md", b["line"], "bydate-format",
                "🔒 bullet missing the ` - *Paywalled*` suffix -> append it",
            )
        if cu in paywalled_topic and b["emoji"] != "🔒":
            repo.error(
                "by-date.md", b["line"], "bydate-format",
                "paper is marked 🔒 in its topic file but not here -> add the 🔒 prefix "
                "and ` - *Paywalled*` suffix",
            )


def check_emoji(repo):
    policy_urls = {
        canon(e["url"]) for stem, _, e in repo.topic_entries() if stem == "policy"
    }
    for stem, sec, e in repo.topic_entries():
        if e["emoji"] == "📄" and stem != "policy":
            repo.error(
                f"learning/{stem}.md", e["line"], "emoji",
                "📄 is reserved for policy documents (learning/policy.md) -> remove it",
            )
    for b in repo.bydate["bullets"]:
        if b["emoji"] == "📄" and canon(b["url"]) not in policy_urls:
            repo.error(
                "by-date.md", b["line"], "emoji",
                "📄 marks policy documents, but this URL is not in learning/policy.md "
                "-> remove the emoji or file the doc under policy",
            )


def check_attribution(repo):
    for b in repo.bydate["bullets"]:
        rest = b["rest"].replace("- *Paywalled*", "")
        if not re.search(r"\([^)]*\d{4}[^)]*\)", rest):
            repo.warn(
                "by-date.md", b["line"], "attribution",
                f'"{b["title"][:50]}" missing "(Authors, Year)" suffix -> add it',
            )
        else:
            m = re.search(r"\((?:[^)]*?,\s*)?(\d{4})(?:/\d{4})?\)", rest)
            if m and b["year"] and abs(int(m.group(1)) - b["year"]) > 1:
                repo.warn(
                    "by-date.md", b["line"], "year-sanity",
                    f'attribution year {m.group(1)} but listed under ## {b["year"]} '
                    "-> check the entry is in the right section",
                )
        # arXiv IDs encode YYMM: catch entries filed under the wrong month
        cu = canon(b["url"])
        if cu.startswith("arxiv:") and b["year"]:
            yy, mm = int(cu[6:8]) + 2000, int(cu[8:10])
            if (yy, mm) != (b["year"], b["month"] or mm):
                repo.warn(
                    "by-date.md", b["line"], "arxiv-date",
                    f"arXiv ID dates this {yy}.{mm:02d} but it is filed under "
                    f'{b["year"]}{"." + format(b["month"], "02d") if b["month"] else ""} '
                    "-> move it (arXiv submission month is authoritative)",
                )


def check_counts(repo):
    c = repo.counts()
    try:
        readme = README.read_text(encoding="utf-8").splitlines()
    except OSError:
        repo.error("README.md", 1, "count", "README.md unreadable")
        return

    sites = {"badge": False, "prose": False, "total": False,
             "areas_badge": False, "glossary_badge": False}
    for i, line in enumerate(readme, 1):
        m = re.search(r"badge/papers-(\d+)-blue", line)
        if m:
            sites["badge"] = True
            if int(m.group(1)) != c["distinct"]:
                repo.error("README.md", i, "count",
                           f'papers badge says {m.group(1)}, actual {c["distinct"]} '
                           "-> run: python3 scripts/validate.py --fix")
        m = re.search(r"badge/learning-(\d+)_areas", line)
        if m:
            sites["areas_badge"] = True
            if int(m.group(1)) != c["areas"]:
                repo.error("README.md", i, "count",
                           f'areas badge says {m.group(1)}, actual {c["areas"]} -> run --fix')
        m = re.search(r"badge/glossary-(\d+)_terms", line)
        if m:
            sites["glossary_badge"] = True
            if int(m.group(1)) != c["glossary_terms"]:
                repo.error("README.md", i, "count",
                           f'glossary badge says {m.group(1)}, actual {c["glossary_terms"]} '
                           "-> run --fix")
        m = re.search(r"\*\*(\d+) carefully selected", line)
        if m:
            sites["prose"] = True
            if int(m.group(1)) != c["distinct"]:
                repo.error("README.md", i, "count",
                           f'prose total says {m.group(1)}, actual {c["distinct"]} -> run --fix')
        m = re.match(r"^\*\*Total\*\*: (\d+) papers across (\d+) areas \(including (\d+) policy", line)
        if m:
            sites["total"] = True
            if (int(m.group(1)), int(m.group(2)), int(m.group(3))) != (
                c["distinct"], c["areas"], c["policy_docs"]
            ):
                repo.error("README.md", i, "count",
                           f'total line says {m.group(1)}/{m.group(2)} areas/{m.group(3)} policy, '
                           f'actual {c["distinct"]}/{c["areas"]}/{c["policy_docs"]} -> run --fix')
        m = re.match(r"^\| \*\*\[[^\]]+\]\(learning/([a-z-]+)\.md\)\*\* \| [^|]+ \| (\d+) \|", line)
        if m:
            stem, n = m.group(1), int(m.group(2))
            if stem in c["per_area"] and n != c["per_area"][stem]:
                repo.error("README.md", i, "count",
                           f'table says {n} papers for {stem}, actual {c["per_area"][stem]} '
                           "-> run --fix")
        m = re.search(r"\b(\d+) terms\b", line)
        if m and int(m.group(1)) != c["glossary_terms"]:
            repo.error("README.md", i, "count",
                       f'says {m.group(1)} terms, glossary has {c["glossary_terms"]} -> run --fix')
    for name, found in sites.items():
        if not found:
            repo.error("README.md", 1, "count",
                       f"expected count site '{name}' not found in README.md "
                       "-> the count check can no longer see it; restore the pattern")

    f = repo.bydate["footer"]
    if "total" in f and f["total"][1] != c["bydate_total"]:
        repo.error("by-date.md", f["total"][0], "count",
                   f'footer total says {f["total"][1]}, actual {c["bydate_total"]} -> run --fix')
    if "paywalled" in f and f["paywalled"][1] != c["bydate_paywalled"]:
        repo.error("by-date.md", f["paywalled"][0], "count",
                   f'footer paywalled says {f["paywalled"][1]}, actual {c["bydate_paywalled"]} '
                   "-> run --fix")
    if "open" in f and c["bydate_total"]:
        expected = round(100 * (1 - c["bydate_paywalled"] / c["bydate_total"]))
        if f["open"][1] != expected:
            repo.error("by-date.md", f["open"][0], "count",
                       f'footer open-access says {f["open"][1]}%, actual ~{expected}% -> run --fix')
    for key in ("total", "paywalled", "open"):
        if key not in f:
            repo.error("by-date.md", 1, "count",
                       f"footer stat '{key}' not found -> restore the footer pattern")


def generate_coverage(repo):
    out = ["This collection spans the full spectrum of modern AI/ML research, organized by area:", ""]
    for stem, emoji, label in AREAS:
        if stem not in repo.topics:
            continue
        out.append(f"### {emoji} {label}")
        for sec in repo.topics[stem]:
            if not sec["entries"]:
                continue
            links = " · ".join(f'[{e["title"]}]({e["url"]})' for e in sec["entries"])
            out.append(f"- **{sec['name']}**: {links}")
        out.append("")
    if out and out[-1] == "":
        out.pop()
    return out


def check_coverage(repo):
    try:
        lines = README.read_text(encoding="utf-8").splitlines()
    except OSError:
        return
    if COVERAGE_START not in lines or COVERAGE_END not in lines:
        repo.error(
            "README.md", 1, "coverage-gen",
            "Coverage by Topic is not marker-managed -> run: python3 scripts/validate.py --fix "
            "(inserts markers and generates the section)",
        )
        return
    start = lines.index(COVERAGE_START)
    end = lines.index(COVERAGE_END)
    current = lines[start + 1:end]
    if current != generate_coverage(repo):
        repo.error(
            "README.md", start + 1, "coverage-gen",
            "generated Coverage by Topic block is stale -> run --fix to regenerate",
        )


# ---------------------------------------------------------------------------
# fixers (mechanical only; each rewrites files, callers re-parse afterwards)
# ---------------------------------------------------------------------------

def fix_numbering():
    for path in sorted(LEARNING.glob("*.md")):
        if path.name == "glossary.md":
            continue
        lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
        counter = 0
        changed = False
        for i, line in enumerate(lines):
            if line.startswith("## "):
                counter = 0
            m = ENTRY_RE.match(line.rstrip("\n"))
            if m:
                counter += 1
                if int(m.group(1)) != counter:
                    lines[i] = re.sub(r"^\d+\.", f"{counter}.", line, count=1)
                    changed = True
        if changed:
            path.write_text("".join(lines), encoding="utf-8")


def fix_missing_bydate(repo):
    """Insert topic entries that are absent from by-date.md under their year."""
    bydate_urls = {canon(b["url"]) for b in repo.bydate["bullets"]}
    missing = []
    for stem, sec, e in repo.topic_entries():
        cu = canon(e["url"])
        if cu in bydate_urls:
            continue
        bydate_urls.add(cu)
        years = re.findall(r"(\d{4})", e["rest"])
        if not years:
            continue  # no parseable year: left for the cross-index error
        emoji = f'{e["emoji"]} ' if e["emoji"] else ""
        suffix = " - *Paywalled*" if e["emoji"] == "🔒" else ""
        attr = e["rest"].strip()
        bullet = f'- {emoji}[{e["title"]}]({e["url"]}) {attr}{suffix}'.rstrip()
        missing.append((int(years[-1]), bullet))
    if not missing:
        return
    lines = BYDATE.read_text(encoding="utf-8").splitlines()
    for year, bullet in missing:
        if not any(re.match(rf"^## {year}$", l) for l in lines):
            # create the year section in descending position
            for i, line in enumerate(lines):
                m = re.match(r"^## (\d{4})$", line)
                if m and int(m.group(1)) < year:
                    lines[i:i] = [f"## {year}", "", bullet, ""]
                    break
            else:
                # older than everything: before the footer separator, else at end
                end = next((i for i in range(len(lines) - 1, -1, -1)
                            if lines[i].strip() == "---"), len(lines))
                lines[end:end] = [f"## {year}", "", bullet, ""]
            continue
        year_idx = None
        for i, line in enumerate(lines):
            if re.match(rf"^## {year}$", line):
                year_idx = i
            elif year_idx is not None and (line.startswith("## ") or line.strip() == "---"):
                insert_at = i
                while insert_at > year_idx and lines[insert_at - 1].strip() == "":
                    insert_at -= 1
                lines.insert(insert_at, bullet)
                break
        else:
            if year_idx is not None:  # year is the last section
                lines.append(bullet)
    BYDATE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def fix_order():
    """Reorder standard ## YYYY sections (desc) and ### YYYY.MM blocks within them."""
    text = BYDATE.read_text(encoding="utf-8")
    lines = text.splitlines()
    # split: preamble, [(heading, block_lines)], footer(from final ---)
    first = next((i for i, l in enumerate(lines) if re.match(r"^## ", l)), None)
    if first is None:
        return
    footer_start = len(lines)
    for i in range(len(lines) - 1, first, -1):
        if lines[i].strip() == "---":
            footer_start = i
            break
    pre, body, post = lines[:first], lines[first:footer_start], lines[footer_start:]
    sections = []  # (year_or_None, [lines])
    cur = None
    for line in body:
        if line.startswith("## ") and not line.startswith("###"):
            m = re.match(r"^## (\d{4})$", line)
            cur = {"year": int(m.group(1)) if m else None, "lines": [line]}
            sections.append(cur)
        elif cur is not None:
            cur["lines"].append(line)
    if any(s["year"] is None for s in sections):
        return  # non-standard year headings present; fix those first
    # inside each year, reorder month blocks
    for s in sections:
        head, rest = s["lines"][0], s["lines"][1:]
        blocks, loose, curb = [], [], None
        for line in rest:
            if line.startswith("### "):
                m = re.match(r"^### (\d{4})\.(\d{2})$", line)
                curb = {"key": (int(m.group(1)), int(m.group(2))) if m else None,
                        "lines": [line]}
                blocks.append(curb)
            elif curb is None:
                loose.append(line)
            else:
                curb["lines"].append(line)
        if any(b["key"] is None for b in blocks):
            continue
        blocks.sort(key=lambda b: b["key"], reverse=True)
        out = [head]
        loose_stripped = [l for l in loose if l.strip()]
        if loose_stripped and not blocks:
            out.extend(loose)
        else:
            out.append("")
            for l in loose_stripped:
                out.append(l)
            if loose_stripped:
                out.append("")
            for b in blocks:
                block = [l for l in b["lines"]]
                while block and block[-1].strip() == "":
                    block.pop()
                out.extend(block)
                out.append("")
        while out and out[-1].strip() == "":
            out.pop()
        s["lines"] = out
    sections.sort(key=lambda s: s["year"], reverse=True)
    new_body = []
    for s in sections:
        new_body.extend(s["lines"])
        new_body.append("")
    result = pre + new_body + post
    BYDATE.write_text("\n".join(result).rstrip("\n") + "\n", encoding="utf-8")


def fix_backlinks(repo):
    topic_urls = repo.topic_urls()
    lines = BYDATE.read_text(encoding="utf-8").splitlines()
    changed = False
    for b in repo.bydate["bullets"]:
        if b["area_target"] is not None:
            continue
        cu = canon(b["url"])
        owners = topic_urls.get(cu)
        if not owners:
            continue
        stem = owners[0][0]
        label = AREA_LABEL.get(stem, stem.replace("-", " ").title())
        idx = b["line"] - 1
        lines[idx] = f"{lines[idx].rstrip()} — [{label}](learning/{stem}.md)"
        changed = True
    if changed:
        BYDATE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def fix_counts(repo):
    c = repo.counts()
    text = README.read_text(encoding="utf-8")
    text = re.sub(r"badge/papers-\d+-blue", f'badge/papers-{c["distinct"]}-blue', text)
    text = re.sub(r"badge/learning-\d+_areas", f'badge/learning-{c["areas"]}_areas', text)
    text = re.sub(r"badge/glossary-\d+_terms", f'badge/glossary-{c["glossary_terms"]}_terms', text)
    text = re.sub(r"\*\*\d+ carefully selected", f'**{c["distinct"]} carefully selected', text)
    text = re.sub(
        r"^\*\*Total\*\*: \d+ papers across \d+ areas \(including \d+ policy[^)]*\)",
        f'**Total**: {c["distinct"]} papers across {c["areas"]} areas '
        f'(including {c["policy_docs"]} policy documents & frameworks)',
        text, flags=re.M,
    )
    text = re.sub(r"\b\d+ terms\b", f'{c["glossary_terms"]} terms', text)

    def table_row(m):
        stem = m.group("stem")
        if stem in c["per_area"]:
            return f'{m.group("pre")}{c["per_area"][stem]}{m.group("post")}'
        return m.group(0)

    text = re.sub(
        r"(?P<pre>^\| \*\*\[[^\]]+\]\(learning/(?P<stem>[a-z-]+)\.md\)\*\* \| [^|]+ \| )\d+(?P<post> \|)",
        table_row, text, flags=re.M,
    )
    README.write_text(text, encoding="utf-8")

    lines = BYDATE.read_text(encoding="utf-8").splitlines()
    open_pct = round(100 * (1 - c["bydate_paywalled"] / c["bydate_total"])) if c["bydate_total"] else 100
    for i, line in enumerate(lines):
        if line.startswith("**Total Papers in Learning Path**:"):
            lines[i] = f'**Total Papers in Learning Path**: {c["bydate_total"]} papers'
        elif line.startswith("**Paywalled Papers**:"):
            lines[i] = f'**Paywalled Papers**: {c["bydate_paywalled"]} (marked with 🔒)'
        elif line.startswith("**Open Access**:"):
            lines[i] = f"**Open Access**: ~{open_pct}%"
    BYDATE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def fix_coverage(repo):
    lines = README.read_text(encoding="utf-8").splitlines()
    generated = generate_coverage(repo)
    if COVERAGE_START in lines and COVERAGE_END in lines:
        start, end = lines.index(COVERAGE_START), lines.index(COVERAGE_END)
        lines[start + 1:end] = generated
    else:
        head = next((i for i, l in enumerate(lines) if l.startswith("## ") and "Coverage by Topic" in l), None)
        if head is None:
            return
        end = next((i for i in range(head + 1, len(lines)) if lines[i].startswith("## ")), len(lines))
        # keep the trailing separator that belongs to the next section
        sep = end
        while sep > head + 1 and lines[sep - 1].strip() in ("", "---"):
            sep -= 1
        block = ["", COVERAGE_START, *generated, COVERAGE_END, "", "---", ""]
        lines[head + 1:end] = block
    README.write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# link checking (--links)
# ---------------------------------------------------------------------------

def run_links():
    import urllib.request
    from concurrent.futures import ThreadPoolExecutor
    from urllib.parse import urlparse

    targets = {}  # url -> (file, line)
    for path in [README, LEARNING_PATH, BYDATE, ROOT / "CONTRIBUTING.md",
                 *sorted(LEARNING.glob("*.md"))]:
        if not path.exists():
            continue
        for i, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            for m in MD_LINK_RE.finditer(line):
                url = m.group(2)
                if url.startswith(("http://", "https://")):
                    targets.setdefault(url, (rel(path), i))

    def check(url):
        host = urlparse(url).netloc
        if host in LINK_SKIP_HOSTS:
            return url, None
        req = urllib.request.Request(
            url, method="HEAD",
            headers={"User-Agent": "papers-repo-validator/1.0 (link check)"})
        for method in ("HEAD", "GET"):
            req = urllib.request.Request(
                url, method=method,
                headers={"User-Agent": "papers-repo-validator/1.0 (link check)"})
            try:
                with urllib.request.urlopen(req, timeout=20) as resp:
                    return url, None if resp.status in LINK_OK_CODES or resp.status < 400 else resp.status
            except Exception as exc:  # noqa: BLE001 - report every failure kind
                code = getattr(exc, "code", None)
                if code in LINK_OK_CODES:
                    return url, None
                last = code if code is not None else exc.__class__.__name__
        return url, last

    failures = []
    with ThreadPoolExecutor(max_workers=8) as pool:
        for url, status in pool.map(check, sorted(targets)):
            if status is not None:
                file, line = targets[url]
                failures.append(f"ERROR {file}:{line} [link] {url} -> {status}")
    skipped = sum(1 for u in targets if urlparse(u).netloc in LINK_SKIP_HOSTS)
    for f in failures:
        print(f)
    print(f"links: {len(failures)} failures, {len(targets)} checked, {skipped} skipped (paywalled hosts)")
    return 1 if failures else 0


# ---------------------------------------------------------------------------
# orchestration
# ---------------------------------------------------------------------------

def self_heal_hookspath(quiet):
    """Per-clone git state is unavoidable; converge it from the repo itself."""
    if not (ROOT / "githooks" / "pre-commit").exists():
        return
    try:
        out = subprocess.run(
            ["git", "-C", str(ROOT), "config", "core.hooksPath"],
            capture_output=True, text=True, timeout=10,
        )
        if out.stdout.strip() != "githooks":
            subprocess.run(
                ["git", "-C", str(ROOT), "config", "core.hooksPath", "githooks"],
                capture_output=True, text=True, timeout=10,
            )
            if not quiet:
                print("note: set git core.hooksPath=githooks (pre-commit validation enabled)")
    except Exception:
        pass


def run_checks():
    repo = Repo()
    check_cross_index(repo)
    check_duplicates(repo)
    check_anchors(repo)
    check_order(repo)
    check_entry_format(repo)
    check_bydate_format(repo)
    check_emoji(repo)
    check_attribution(repo)
    check_counts(repo)
    check_coverage(repo)
    repo.findings.sort(key=lambda f: (f.file, f.line, f.check))
    return repo


def report(repo, stream=sys.stdout):
    errors = sum(1 for f in repo.findings if f.severity == "ERROR")
    warns = len(repo.findings) - errors
    for f in repo.findings:
        print(f.render(), file=stream)
    files = len({f.file for f in repo.findings})
    print(f"validate: {errors} errors, {warns} warnings in {files} files", file=stream)
    return errors


def run_fix():
    fix_numbering()
    repo = Repo()
    fix_missing_bydate(repo)
    fix_order()
    repo = Repo()
    fix_backlinks(repo)
    repo = Repo()
    fix_counts(repo)
    repo = Repo()
    fix_coverage(repo)
    return run_checks()


RELEVANT = ("README.md", "by-date.md", "learning-path.md", "CONTRIBUTING.md")


def run_hook(mode):
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0
    try:
        if mode == "stop" and payload.get("stop_hook_active"):
            return 0
        if mode == "post-tool-use":
            file_path = str((payload.get("tool_input") or {}).get("file_path", ""))
            name = Path(file_path).name
            in_learning = "/learning/" in file_path and file_path.endswith(".md")
            if not (name in RELEVANT or in_learning):
                return 0
        self_heal_hookspath(quiet=True)
        repo = run_checks()
        errors = [f for f in repo.findings if f.severity == "ERROR"]
        if errors:
            # digest for the agent: capped, errors only — full list via manual run
            for f in errors[:25]:
                print(f.render(), file=sys.stderr)
            if len(errors) > 25:
                print(f"... and {len(errors) - 25} more errors "
                      "(run: python3 scripts/validate.py)", file=sys.stderr)
            print(
                f"validate: {len(errors)} errors. Each line ends with a fix hint; "
                "mechanical issues: run `python3 scripts/validate.py --fix`.",
                file=sys.stderr,
            )
            return 2
        return 0
    except Exception:
        return 0  # fail open: a validator bug must never brick editing


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fix", action="store_true", help="apply mechanical fixes")
    parser.add_argument("--hook", choices=["post-tool-use", "stop"], help="Claude Code hook mode")
    parser.add_argument("--links", action="store_true", help="check external links (network)")
    args = parser.parse_args()

    if args.hook:
        sys.exit(run_hook(args.hook))
    try:
        self_heal_hookspath(quiet=False)
        if args.links:
            sys.exit(run_links())
        repo = run_fix() if args.fix else run_checks()
        errors = report(repo)
        sys.exit(1 if errors else 0)
    except KeyboardInterrupt:
        sys.exit(3)
    except Exception as exc:  # noqa: BLE001
        print(f"validate: internal error: {exc!r}", file=sys.stderr)
        sys.exit(3)


if __name__ == "__main__":
    main()
